language: python
python:
    - "3.7"
env:
    - QT_QPA_PLATFORM=offscreen
install:
    - sudo apt-get update
    - pip install -U pip setuptools wheel
    - pip install -r requirements.txt
    - pip install PyQt5
    - pip install -e .
script:
    pytest tests
 